$('#btn1').click(function(){
    $('p').fadeOut();
    $('p').fadeIn();
    $('p').fadeOut();
    $('p').fadeIn();
    $('p').fadeOut();
    $('p').fadeIn();
    $('p').fadeOut();
    $('p').fadeIn();
    $('p').fadeOut();
    $('p').fadeIn();
    $('p').fadeOut();
    $('p').fadeIn();
    $('p').fadeOut();
    $('p').fadeIn();
});
$("#btn2").click(function(){
    $('p').fadeOut();
    $('p').fadeIn();
    $("section.section-counter").animate({borderBottomWidth:"10px"});
    });